name: Go Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  golangci-lint:
    name: Run Go Linter
    runs-on: ubuntu-latest
    # 跳过 Draft PR
    if: github.event.pull_request.draft == false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **/*.go
          go.mod
          go.sum
        files_ignore: |
          **/*.md
          **/*.yml
          **/*.yaml

    - name: Set up Go
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Run golangci-lint
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m
        only-new-issues: true
